[2025-04-26 20:29:12,967][zerorpc.core][ERROR] - 
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "reactive_tamp.py", line 131, in run_tamp
    self.motion_planner.command(self.sim._dof_state[0])[0]
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 246, in command
    cost_total = self._compute_total_cost_batch_halton()
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 426, in _compute_total_cost_batch_halton
    self.cost_total, self.states, self.actions, self.ee_states = self._compute_rollout_costs(self.perturbed_action)
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 308, in _compute_rollout_costs
    state, u = self._dynamics(state, u, t)
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 208, in _dynamics
    return self.F(state, u, t=None)
  File "reactive_tamp.py", line 136, in dynamics
    self.sim.step1()
AttributeError: 'IsaacGymWrapper' object has no attribute 'step1'
[2025-04-26 20:30:12,584][zerorpc.core][ERROR] - 
Traceback (most recent call last):
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/my/anaconda3/envs/m3p2i-aip/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "reactive_tamp.py", line 131, in run_tamp
    self.motion_planner.command(self.sim._dof_state[0])[0]
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 246, in command
    cost_total = self._compute_total_cost_batch_halton()
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 426, in _compute_total_cost_batch_halton
    self.cost_total, self.states, self.actions, self.ee_states = self._compute_rollout_costs(self.perturbed_action)
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 308, in _compute_rollout_costs
    state, u = self._dynamics(state, u, t)
  File "/home/my/Hindsight-Goal-Generation-master4/Hindsight-Goal-Generation-master/m3p2i_aip/planners/motion_planner/mppi.py", line 208, in _dynamics
    return self.F(state, u, t=None)
  File "reactive_tamp.py", line 136, in dynamics
    self.sim.step()
AttributeError: 'IsaacGymWrapper' object has no attribute 'step1'
